servos:
  - servo: 1
    center: 316
    range: 170
    direction: 1
  - servo: 2
    center: 316
    range: 170
    direction: 1
  - servo: 3
    center: 316
    range: 170
    direction: 1
  - servo: 4
    center: 316
    range: 170
    direction: 1
  - servo: 5
    center: 316
    range: 170
    direction: 1